<div class="card">
	<div class="card-header">
		<h3 class="card-title col-12 text-center">Delete Data User</h3>
	</div>
	<form class="form-horizontal" action="" method="post">
		<div class="card-body">
			<div class="form-group row">
				<label for="username" class="col-sm-2 col-form-label">Username</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="username" name="username" placeholder="Username" required autofocus value="<?=$user->username?>" disabled>
				</div>
			</div>
            <div class="form-group row">
				<label for="level_user" class="col-sm-2 col-form-label">Level</label>
				<div class="col-sm-10">
					<select class="select2 form-control" name="level_user" required autofocus disabled>
                        <option value="">Pilih Level</option>
                        <option <?= ($user->level_user == 'dosen') ? 'selected':'' ?> value="dosen">Dosen</option>
                        <option <?= ($user->level_user == 'mahasiswa') ? 'selected':'' ?> value="mahasiswa">Mahasiswa</option>
                    </select>
				</div>
			</div>

			<div class="form-group row">
				<div class="row offset-sm-2 col-sm-10">
					<div class="col-6 pl-0">
						<a href="<?=$this->url->get('user')?>">
							<button type="button" class="btn btn-warning col-12">Cancel</button>
						</a>
					</div>
					<div class="col-6 pr-0">
						<button type="submit" name="submit" class="btn btn-danger col-12" onclick="return confirm('Apakah anda yakin akan menghapus user ini?')">Delete User</button>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>
