<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title><?=$title?></title>
	<!-- Tell the browser to be responsive to screen width -->
	<meta
	name="viewport" content="width=device-width, initial-scale=1">
	<!-- Font Awesome -->
	<link
	rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/fontawesome-free/css/all.min.css">
	<!-- Ionicons -->
	<link
	rel="stylesheet" href="<?=$this->url->get();?>public/download/ionicons-2.0.1/css/ionicons.min.css">
	<!-- Tempusdominus Bbootstrap 4 -->
	<link
	rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
	<!-- iCheck -->
	<link
	rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
	<!-- JQVMap -->
	<link
	rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/jqvmap/jqvmap.min.css">

	<!-- Select2 -->
    <link rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/select2/css/select2.min.css">

	<!-- Theme style -->
	<link
	rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/dist/css/adminlte.min.css">
	<!-- overlayScrollbars -->
	<link
	rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
	<!-- Daterange picker -->
	<link
	rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/daterangepicker/daterangepicker.css">
	<!-- summernote -->
	<link
	rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/summernote/summernote-bs4.css">
	<!-- Google Font: Source Sans Pro -->
	<link href="<?=$this->url->get();?>public/download/font-google/font-family.css" rel="stylesheet">

	<!-- Data Table  -->
    <link rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">

    <link rel="shortcut icon" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/dist/img/AdminLTELogo.png" type="image/x-icon">
    <!-- <link rel="stylesheet" href="<?=$this->url->get();?>public/AdminLTE-3.0.5/plugins/datatables/buttons.dataTables.min.css"> -->
</head>
